apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: push
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user
          image: docker.io/mmmdliayxan321/ms-user-1:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: logging-config-volume
              mountPath: /app/config/logging.json
              subPath: logging.json
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ms-user-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: ms-user-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-user-secret
                  key: SPRING_DATASOURCE_PASSWORD
      volumes:
        - name: logging-config-volume
          configMap:
            name: logging-config
            items:
              - key: logging.json
                path: logging.json

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: ms-user-expiry-check
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: expiry-checker
              image: curlimages/curl:latest
              args:
                - curl
                - -X
                - POST
                - http://ms-user:8081/internal/check-user-expiry
          restartPolicy: OnFailure
