apiVersion: v1
kind: ServiceAccount
metadata:
  name: keel
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "replicationcontrollers", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keel
subjects:
  - kind: ServiceAccount
    name: keel
    namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: kube-system
spec:
  selector:
    app: keel
  ports:
    - protocol: TCP
      port: 9300
      targetPort: 9300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keel
  template:
    metadata:
      labels:
        app: keel
    spec:
      serviceAccountName: keel
      containers:
        - name: keel
          image: keelhq/keel:latest
          ports:
            - containerPort: 9300
          env:
            - name: KEEL_POLICY
              value: "force"
            - name: KEEL_NAMESPACE
              value: ""
            - name: KEEL_TAG_SCOPE
              value: "global"
