name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Docker Build (skip tests)
        run: docker build --build-arg SKIP_TESTS=true -t ${{ secrets.DOCKER_USERNAME }}/ms-user-1:latest .

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ms-user-1:latest


